steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: 'Thank you very much for contributing to Abbreve and opening this issue to make the app better! If you have any questions or queries, start a discussion or reach out to the creator on twitter @njong_emy'
    pr-message: 'Looks like this is your very first pull request! Thank you so much for contributing to Abbreve. If you have any questions or queries, start a discussion or reach out to the creator on twitter @njong_emy'
